version: 1.36.4.{build}
image: Visual Studio 2017
clone_folder: C:\Projects\MaterialX

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      GENERATOR_NAME: vs2015
      configuration: Release
      ARCH: Win32
      PYTHON: C:\Python27
    - GENERATOR: "Visual Studio 14 2015"
      GENERATOR_NAME: vs2015
      configuration: Release
      ARCH: x64
      PYTHON: C:\Python27-x64
    - GENERATOR: "Visual Studio 15 2017"
      GENERATOR_NAME: vs2017
      configuration: Release
      ARCH: Win32
      PYTHON: C:\Python36
    - GENERATOR: "Visual Studio 15 2017"
      GENERATOR_NAME: vs2015
      configuration: Release
      ARCH: x64
      PYTHON: C:\Python37-x64

install:
  - set PATH=%PYTHON%;%PATH%
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_BUILD_VIEWER=ON -DMATERIALX_WARNINGS_AS_ERRORS=ON -G "%GENERATOR%" -A "%ARCH%" ..
  - cmake --build . --target install --config %CONFIGURATION%
  - ctest -VV --output-on-failure --build-config %CONFIGURATION% -j %NUMBER_OF_PROCESSORS%
  - cmake -E chdir ../python/MaterialXTest python main.py
  - cmake -E chdir ../python/MaterialXTest python genshader.py

before_deploy:
    # Go to install directory and zip it up.  Currently marked as pre-release
    - cd C:\Projects\MaterialX\build\installed
    - 7z a -r C:\Projects\MaterialX\materialx-v1.36.4_shaderx-%ARCH%-%GENERATOR_NAME%-%CONFIGURATION%.zip .

artifacts:
    # Set artifact to be created zip.  Currently marked as pre-release
    - path: materialx-v1.36.4_shaderx-%ARCH%-%GENERATOR_NAME%-%CONFIGURATION%.zip
      name: MaterialX_ADSK

deploy:
    # Deploy on "release" branch
    - provider: GitHub
      prerelease: true
      on:
        VS_PLATFORM: Windows
        branch: adsk_contrib/release
      auth_token:
        secure: qg4BvNKremS4OMcbGZEjaXrumrQ+8/pJvr3WrNqM1ZQDyzvNpmUEA0ZMRkUJzeOh

    # Deploy on tags -- only works with master branch
    #- provider: GitHub
    #  prerelease: true
    #  #tag: $(APPVEYOR_REPO_TAG_NAME)
    #  on:
    #    VS_PLATFORM: Windows
    #    APPVEYOR_REPO_TAG: true
    #  auth_token:
    #    secure: qg4BvNKremS4OMcbGZEjaXrumrQ+8/pJvr3WrNqM1ZQDyzvNpmUEA0ZMRkUJzeOh
