name: build_mac

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

  build_mac:
    name: Build_Mac
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: MacOS_Xcode_10_Python27
          os: macos-10.15
          compiler: xcode
          compiler_version: "10.3"
          python: 2.7
          cmake_config: -DMATERIALX_PYTHON_VERSION=2 -DMATERIALX_BUILD_SHARED_LIBS=ON

        - name: MacOS_Xcode_11_Python37
          os: macos-10.15
          compiler: xcode
          compiler_version: "11.7"
          python: 3.7

        - name: MacOS_Xcode_12_Python37
          os: macos-10.15
          compiler: xcode
          compiler_version: "12.2"
          python: 3.7

    steps:
    - name: Sync Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies (MacOS)
      if: runner.os == 'macOS'
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          brew install gcc@${{ matrix.compiler_version }}
          echo "CC=gcc-${{ matrix.compiler_version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.compiler_version }}" >> $GITHUB_ENV
        else
          ls -ls /Applications/
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.compiler_version }}.app
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        fi

    - name: Install Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: Create Build Directory
      run: mkdir build
      
    - name: CMake Generate
      run: cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_BUILD_VIEWER=ON -DMATERIALX_TEST_RENDER=OFF -DMATERIALX_WARNINGS_AS_ERRORS=ON ${{matrix.cmake_config}} ..
      working-directory: build

    - name: CMake Build
      run: cmake --build . --target install --config Release --parallel 2
      working-directory: build

    - name: Initialize Virtual Framebuffer
      if: matrix.test_render == 'ON' && runner.os == 'Linux'
      run: |
        Xvfb :1 -screen 0 1280x960x24 &
        echo "DISPLAY=:1" >> $GITHUB_ENV
        echo "MESA_GL_VERSION_OVERRIDE=4.0FC" >> $GITHUB_ENV
        echo "MESA_GLSL_VERSION_OVERRIDE=400" >> $GITHUB_ENV
        echo "GALLIUM_DRIVER=softpipe" >> $GITHUB_ENV

    - name: CMake Unit Tests
      run: ctest -VV --output-on-failure --build-config Release
      working-directory: build

    - name: Python Tests
      run: |
        python MaterialXTest/main.py
        python MaterialXTest/genshader.py
        python Scripts/mxupdate.py ../resources/Materials/TestSuite/stdlib/upgrade --yes
        python Scripts/mxvalidate.py ../resources/Materials/Examples/StandardSurface/standard_surface_marble_solid.mtlx --verbose
        python Scripts/mxdoc.py ../libraries/pbrlib/pbrlib_defs.mtlx
      working-directory: python

    - name: Render Tests
      if: matrix.test_render == 'ON'
      run: |
        mkdir build/render
        python python/Scripts/baketextures.py resources/Materials/Examples/StandardSurface/standard_surface_brass_tiled.mtlx build/render/brass_tiled_baked.mtlx --path .
        python python/Scripts/baketextures.py resources/Materials/Examples/StandardSurface/standard_surface_brass_tiled.mtlx build/render/brass_average_baked.mtlx --average --path .
        build/installed/bin/MaterialXView --material build/render/brass_average_baked.mtlx --mesh resources/Geometry/sphere.obj --screenWidth 128 --screenHeight 128 --cameraZoom 1.4 --captureFilename build/render/Viewer_BrassAverage.png

    - name: Upload Installed Package
      uses: actions/upload-artifact@v2
      with:
        name: MaterialX_${{ matrix.name }}
        path: build/installed/

    - name: Upload Renders
      uses: actions/upload-artifact@v2
      if: matrix.test_render == 'ON'
      with:
        name: Renders_${{ matrix.name }}
        path: build/render/
